export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const FETCHING_USERS = 'FETCHING_USERS';
export const RECEIVED_USERS = 'RECEIVED_USERS';

export const FETCHING_PRODUCTS = 'FETCHING_PRODUCTS';
export const RECEIVED_PRODUCTS = 'RECEIVED_PRODUCTS';

export const GO_TO_STEP = 'GO_TO_STEP';

export const CHANGE_USERNAME = 'CHANGE_USERNAME';
export const CHANGE_BALANCE = 'CHANGE_BALANCE';
