export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const FETCHING_USERS = 'FETCHING_USERS';
export const RECEIVED_USERS = 'RECEIVED_USERS';

export const FETCHING_PRODUCTS = 'FETCHING_PRODUCTS';
export const RECEIVED_PRODUCTS = 'RECEIVED_PRODUCTS';

export const START_ADDING_NEW_STOCK = 'START_ADDING_NEW_STOCK';
export const STOP_ADDING_NEW_STOCK = 'STOP_ADDING_NEW_STOCK';
export const CHANGE_NEW_STOCK_ID = 'CHANGE_NEW_STOCK_ID';
export const CHANGE_NEW_STOCK_SEARCH = 'CHANGE_NEW_STOCK_SEARCH';
export const CHANGE_NEW_STOCK_QUANTITY = 'CHANGE_NEW_STOCK_QUANTITY';
export const CHANGE_NEW_STOCK_PRICE = 'CHANGE_NEW_STOCK_PRICE';

export const GO_TO_STEP = 'GO_TO_STEP';

export const SEARCH_USERNAME = 'SEARCH_USERNAME';
export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';

export const CHANGE_BALANCE = 'CHANGE_BALANCE';
